version: '3.8'

volumes:
  urban_utopia_2024_database_volume:
  urban_utopia_2024_static_volume:
  urban_utopia_2024_media_volume:

services:

  urban_utopia_2024_database:
    image: postgres:15-alpine
    volumes:
      - urban_utopia_2024_database_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  urban_utopia_2024_redis:
    image: redis:7.2.1-alpine

  urban_utopia_2024_backend:
    image: thesuncatcher222/urban_utopia_2024_backend:latest
    env_file: .env
    volumes:
      - urban_utopia_2024_static_volume:/app/static
      - urban_utopia_2024_media_volume:/app/media
    depends_on:
      - urban_utopia_2024_database
      - urban_utopia_2024_redis

  # urban_utopia_2024_frontend:
  #   image: thesuncatcher222/urban_utopia_2024_frontend:latest
  #   volumes:
  #     - urban_utopia_2024_static_volume:/app/dist
  #   depends_on:
  #     - urban_utopia_2024_backend

  urban_utopia_2024_gateway:
    image: thesuncatcher222/urban_utopia_2024_gateway:latest
    ports:
      - "8005:8000"
    volumes:
      - urban_utopia_2024_static_volume:/var/html/static/
      - urban_utopia_2024_media_volume:/var/html/media/
    depends_on:
      - urban_utopia_2024_backend
      # - urban_utopia_2024_frontend
