FROM nginx:1.19.3-alpine

LABEL description="Urban Utopia 2024 (Gateway)" \
      version="1.0" \
      maintainer="TheSuncatcher222" \
      deployer="https://github.com/TheSuncatcher222/"

COPY nginx.conf /etc/nginx/templates/default.conf.template
