##########################################################################
################################ ENDPOINTS ###############################
##########################################################################


@appeals = http://127.0.0.1:8000/api/v1/appeals/

@auth = http://127.0.0.1:8000/api/v1/token/

@news = http://127.0.0.1:8000/api/v1/news/

@users = http://127.0.0.1:8000/api/v1/users/



##########################################################################
################################# TOKENS #################################
##########################################################################

@admin_access = admin_token_access
@admin_refresh = admin_token_refresh

@ivan_access =  ivan_token_access
@ivan_refresh = ivan_token_refresh


###
POST {{auth}}create/ HTTP/1.1
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin"
}

###
POST {{users}} HTTP/1.1
Content-Type: application/json

{
  "email": "custom.user.3@email.com",
  "password": "CustomPass!1",
  "first_name": "Иван",
  "mid_name": "Иванович",
  "last_name": "Иванов-Сергеев",
  "phone": "+7 911 375 75 73"
}

###
POST {{auth}}create/ HTTP/1.1
Content-Type: application/json

{
  "email": "custom.user.1@email.com",
  "password": "CustomPass!1"
}


##########################################################################
################################## TOKEN #################################
##########################################################################

###
POST {{auth}}create/ HTTP/1.1
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin"
}

###
POST {{auth}}refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "admin_toke_refresh"
}


##########################################################################
################################## NEWS ##################################
##########################################################################

###
POST {{news}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer admin_token_access
# Authorization: Bearer ivan_token_access

{
  "category": "Water",
  "text": "У нас важные новости (1)!",
  "address": {
    "city": "Екатеринбург",
    "district": "Центральный",
    "street": "Ростовская",
    "house": 12,
    "building": "1С",
    "entrance": 2,
    "floor": 11,
    "apartment": 11,
    "index": 199234,
    "latitude": 10.1234,
    "longitude": 11.1
  },
  "quiz": {
    "title": "Опрос №1",
    "answers": [
      "Ответ №1",
      "Ответ №2"
    ]
  }
}


##########################################################################
################################# APPEAL ##################################
##########################################################################

###
POST {{appeals}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer admin_token_access
# Authorization: Bearer ivan_token_access

{
  
}


##########################################################################
################################# USERS ##################################
##########################################################################

###
POST {{users}} HTTP/1.1
Content-Type: application/json

{
  "email": "custom.user.1@email.com",
  "password": "CustomPass!1",
  "first_name": "Иван ",
  "last_name": "Иванов-Сергеев",
  "phone": "+7 911 375 75 75"
}

###
GET {{users}} HTTP/1.1
Authorization: Bearer admin_token_access
# Authorization: Bearer ivan_token_access

###
GET {{users}}?is_municipal=true HTTP/1.1
Authorization: Bearer admin_token_access
# Authorization: Bearer ivan_token_access

###
GET {{users}}1/ HTTP/1.1
Authorization: Bearer admin_token_access
# Authorization: Bearer ivan_token_access
